@baseUrl = https://contacts-api-kxh6.onrender.com/

### Get all contacts
GET https://contacts-api-kxh6.onrender.com/contacts

### Get single contact
GET https://contacts-api-kxh6.onrender.com/contacts/68e3b7be19852c99c322b97d