// LOCALHOST ### Get all users GET http://localhost:3000/users

@baseUrl = https://contacts-api-kxh6.onrender.com/

### Get all contacts
GET https://contacts-api-kxh6.onrender.com/contacts

### Get single contact
GET https://contacts-api-kxh6.onrender.com/contacts/68e3b7be19852c99c322b97d

### 🆕 Create new contact
POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "firstName": "Beauty",
  "lastName": "Austin",
  "email": "beauty.austin@gmail.com",
  "favoriteColor": "Yellow",
  "birthday": "1998-07-14"
}

### 🆕 Update contact
PUT {{baseUrl}}/contacts/68e3b7be19852c99c322b97d

Content-Type: application/json

{
  "favoriteColor": "Purple",
  "firstName": "BB Baby"
}

### 🆕 Delete contact
DELETE {{baseUrl}}/contacts/68e3b9cf19852c99c322b97e

### LOCALHOST ### Add sample data
 GET http://localhost:3000/users